version: '3.8'

services:
  app:
    container_name: service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: maksimkalinin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coinbase
    ports:
      - "5432:5432"
    volumes:
      - ./deploy/migrations/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U maksimkalinin -d coinbase" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

