version: '3.8'

services:
  app:
    container_name: service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db


  db:
    image: postgres:16
    environment:
      POSTGRES_USER: maksimkalinin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coinbase
    ports:
      - "5432:5433"
    volumes:
      - ./deploy/migrations/postgres:/docker-entrypoint-initdb.d
    restart: always

